name: Generate Doxygen Docs

on:
  push:
    branches:
      - main

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Deploy to docs/ folder
        run: |
          mkdir -p tmp-docs
          mv docs/html/* tmp-docs/
          rm -rf docs
          mkdir docs
          mv tmp-docs/* docs/

      - name: Commit and push documentation
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs
          git commit -m "Update documentation" || echo "No changes to commit"
          git push