# .github/workflows/run-tests.yml

name: longdeepsleep tests (CMake)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configure with CMake
        working-directory: test
        run: cmake .

      - name: Build tests
        working-directory: test
        run: cmake --build .

      - name: Run tests
        working-directory: test
        run: ./run_tests
